# Generated by Django 3.2.8 on 2021-11-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20211104_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='quantity_specific',
            field=models.CharField(blank=True, max_length=60, verbose_name='Специфика колонки количества (прим. больше5=6,>10=6)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_column_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название товарного блока (для XML)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price_colunmn_number',
            field=models.CharField(max_length=30, verbose_name='Колонка цены'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quantity_colunmn_number',
            field=models.CharField(max_length=30, verbose_name='Колонка количества'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sku_colunmn_number',
            field=models.CharField(max_length=30, verbose_name='Колонка артикула'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='types',
            field=models.CharField(choices=[('XML', 'XML'), ('XLS', 'Excel')], default='XLS', max_length=32, verbose_name='Тип загрузочного файла'),
        ),
    ]
