# Generated by Django 3.2.8 on 2021-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20211104_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='old_price_colunmn_number',
            field=models.CharField(default='', max_length=30, verbose_name='Колонка цены до применения скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='price_type',
            field=models.CharField(choices=[('pure_price', 'Только цена'), ('pure_and_special_price', 'Цена обычная и цена акционная'), ('pure_and_discount_percent_price', 'Цена обычная и процент скидки')], default='pure_price', max_length=32, verbose_name='Тип обновления цены'),
        ),
    ]
